### ISSUE TITLE
Boot ok, but error on Catalina installation

### ISSUE THREAD

**Issue by Korvenwin** [czombos/asus-rog-strix-z390-i-gaming#16]
My hardware is almost the same as yours, so the Clover boot is ok.

My **BIG** problem occurs installing Catalina.

I erase the disk (tested on a NVMe SSD and SATA HD), with one partition formated as APFS. After 2 or 3 minutes, I receive always the same error: "_An error occurred while preparing the installation. Try running this application again_."

Opening the log, this always occurs after this message:
"_disk26s1 is not convertible to APFS: You may not install to this volume because it can not be converted to Apple File System (APFS)_"

Opening a terminal, a "_diskutil list_" reveals that disk26 is "_Apple_HFS macOS Base System_".

I'm totally without ideas. Any suggestion? Help please and thank you for your work.

**Comment by kwuster** [comment]
What SSDs are you using? You do have there exact model/ SKU? Also have you taken steps to update the firmwares on those drive? Hackinoshes and Macs are very picky about the type of SSDs they support. Also is your question related to OpenCore or Clover? Are you using the same Motherboard as CZOMBO? and is your motherboard running the latest BIOS firmware? These are all the things I would do first. I have templated my OpenCore Hackontsoh 10.15.4 on CZOMBO's repo, and it all checks out fine, even after my detailed look inside the config.plist and SSDT line by line. If you are using PM981 or PM961 SSDs, then you are shit-out-of-luck, these are known to have issues with MacOS. the 970 Evo Plus also has similar problems, but can be fixed with firmware update via Samsung Magican. The only issues I've had with combos repo was the USBMap. I have opted to use the USB-C front panel so the map is quite different to czombos'. Also it might actually be easier if you install MacOS via a real Mac off an external USB first and then clone into the NVMe. Saves time troubleshooting the installer over USB.

**Comment by sowson** [comment]
@kwuster I am sorry this is off topic but how to enable USB-C front panel? do you have a fork or sth with this... btw I am using M.2 WD Black 2TB and it works super nice... wonder If 2 M.2 discs can be in BIOS combined by RAID0? my fork is at https://github.com/sowson/hackintosh only TODO is the USB-C front panel.

**Comment by sowson** [comment]
@Korvenwin hi, on my fork https://github.com/sowson/hackintosh you can find OpenCore EFI for installation, it is a bit different than EFI you use for this spec... and install works for me fine. Look on my fork maybe spec is fine for you... pls let me know! Thanks!

**Comment by kwuster** [comment]
> @kwuster I am sorry this is off topic but how to enable USB-C front panel? do you have a fork or sth with this... btw I am using M.2 WD Black 2TB and it works super nice... wonder If 2 M.2 discs can be in BIOS combined by RAID0? my fork is at https://github.com/sowson/hackintosh only TODO is the USB-C front panel.

@sowson I've Open a topic regarding your USB issues with front panel.

https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/issues/17#issue-606923909

**Comment by kwuster** [comment]
> @kwuster I am sorry this is off topic but how to enable USB-C front panel? do you have a fork or sth with this... btw I am using M.2 WD Black 2TB and it works super nice... wonder If 2 M.2 discs can be in BIOS combined by RAID0? my fork is at https://github.com/sowson/hackintosh only TODO is the USB-C front panel.

I've not had good reliability with WD, but that was years ago I had issue with them. Things might have changed.

I'm using x1 960 PRO SSD from Samsung on the front, and x1 970 Evo Plus SSD on the rear slot at 1TB a piece. I've not tried to RAID0 this, but I don't have any immediate need to.

When I do, I'll update this thread.

**Comment by kwuster** [comment]
> My hardware is almost the same as yours, so the Clover boot is ok.
> 
> My **BIG** problem occurs installing Catalina.
> 
> I erase the disk (tested on a NVMe SSD and SATA HD), with one partition formated as APFS. After 2 or 3 minutes, I receive always the same error: "_An error occurred while preparing the installation. Try running this application again_."
> 
> Opening the log, this always occurs after this message:
> "_disk26s1 is not convertible to APFS: You may not install to this volume because it can not be converted to Apple File System (APFS)_"
> 
> Opening a terminal, a "_diskutil list_" reveals that disk26 is "_Apple_HFS macOS Base System_".
> 
> I'm totally without ideas. Any suggestion? Help please and thank you for your work.

You might be better off to try formatting you disk a APFS from the beginning and not HFS+ under GUID scheme. This will bypass the APFS conversion step in the installer.

**Comment by sowson** [comment]
@kwuster I have now USB-C enabled USB 2.0 does not matter to me :D... you made my day by https://github.com/czombos/asus-rog-strix-z390-i-gaming-hackintosh/issues/17 thanks! :D

**Comment by Korvenwin** [comment]
Firs of all, thank you very much to everybody for your quick replies.

> What SSDs are you using? You do have there exact model/ SKU? Also have you taken steps to update the firmwares on those drive? Hackinoshes and Macs are very picky about the type of SSDs they support. Also is your question related to OpenCore or Clover? Are you using the same Motherboard as CZOMBO? and is your motherboard running the latest BIOS firmware? These are all the things I would do first. I have templated my OpenCore Hackontsoh 10.15.4 on CZOMBO's repo, and it all checks out fine, even after my detailed look inside the config.plist and SSDT line by line. If you are using PM981 or PM961 SSDs, then you are shit-out-of-luck, these are known to have issues with MacOS. the 970 Evo Plus also has similar problems, but can be fixed with firmware update via Samsung Magican. The only issues I've had with combos repo was the USBMap. I have opted to use the USB-C front panel so the map is quite different to czombos'. Also it might actually be easier if you install MacOS via a real Mac off an external USB first and then clone into the NVMe. Saves time troubleshooting the installer over USB.

- I'm using a Samsung 970 EVO NVMe updated to the most recent firmware. I've tried a 2.5" HDD connected via SATA6 with identical results. Off topic: I'm planning to get a bigger one, perhaps Crucial P1, any comment?
- By now, I'm using Clover because I still don't know how exactly works OpenCore. 
- My motherboard is the ASUS ROG STRIX Z390-I GAMING with most recent BIOS tool.
- One stranger thing I've noticed is after get this error and doing a Shutdown from the Apple Menu, My BIOS gives me a "System has POSTed in safe mode" error and request to press F1 Setup.

I will try your setup, as soon I undestarnd how to make OpenCore works.

> @Korvenwin hi, on my fork https://github.com/sowson/hackintosh you can find OpenCore EFI for installation, it is a bit different than EFI you use for this spec... and install works for me fine. Look on my fork maybe spec is fine for you... pls let me know! Thanks!

Can you please give me a link where is explained how to setup OpenCore? I'm a bit confused about it.

> You might be better off to try formatting you disk a APFS from the beginning and not HFS+ under GUID scheme. This will bypass the APFS conversion step in the installer.

Before any installation procedure, I use Disk Utility to Erase disk as AFPS with GUID scheme.

**Comment by kwuster** [comment]
@Korvenwin you can look at the following [guide](https://dortania.github.io/OpenCore-Desktop-Guide/) for details on OpenCORE.

You should just be able to drag and drop @czombos OpenCORE EFI in the EFI partition on the booting drive and it should work 95%. You'll need to change your Platform SMBIOS stuff and the USBMap to match your hardware. All are detailed in the "[Dortania](https://dortania.github.io/OpenCore-Desktop-Guide/)" guide.

> One stranger thing I've noticed is after get this error and doing a Shutdown from the Apple Menu, My BIOS gives me a "System has POSTed in safe mode" error and request to press F1 Setup.

This is a strange one, and I am still trying to find ways around it, but not have the time. Ever since I updated to the latest [BIOS 2603](https://www.asus.com/Motherboards/ROG-STRIX-Z390-I-GAMING/HelpDesk_BIOS/), and used the additional fixes found relating to USB Sleep/ Shutdown from [@simoncoulton](https://github.com/simoncoulton/opencore-asus-rog-strix-z390i), I found this to be less frequent, but I don't think this is the fix as it comes back every now and then.

My research has pointed me to an RTC (Real-time clock) issue coming from MacOS 10.15.4. The issue arose due to something MacOS is writing additional 'stuff' to the RTC memory at boot.

The general consensus to use [RTCMemoryFixup.kext](https://www.asus.com/Motherboards/ROG-STRIX-Z390-I-GAMING/HelpDesk_BIOS/) if you are using 10.15.4. RTCMemoryFixup blocks/ offsets the RTC memory address space to stop MacOS from writing to them. It's a hack, a real fix would come in the from of a BIOS firmware customisation.

You might also look at the patches inside the [Sample.plist](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist) from the OpenCorePkg repo relating to "RTC".

Again, these are the directions I am looking to take, but not yet had time to investigate fully. I've just live with it for now by setting my BIOS to **not** require 'F1' when POST failed. Of course, at your own risk. I'm starting a new issue based on this as it is off-topic.

**Comment by Korvenwin** [comment]
I've followed the guide you suggest in a real Mac. I create the Catalina installer, mount EFI and copy the files inside the partition, but I cannot understand how to 'install the booloder' like Clover do withi the pkg installer.

**Comment by Korvenwin** [comment]
Oh, great!! I see it is not necesary install anything. I only have to copy @sowson EFI folder. Is that right?

**Comment by kwuster** [comment]
> I've followed the guide you suggest in a real Mac. I create the Catalina installer, mount EFI and copy the files inside the partition, but I cannot understand how to 'install the booloder' like Clover do withi the pkg installer.

No. I mean use a real Mac, boot into it using a real Mac, until you can successfully enter the desktop via the real Mac. Then you can start adding the EFI folder to the EFI partition. That way you skip having to use the installer on your Hackintosh.

Best use an external USB case. I have an m.2 M-Key to do this, but you should be able to use a 2.5" USB 3.0 external case to do the same thing.

**Comment by kwuster** [comment]
> Oh, great!! I see it is not necesary install anything. I only have to copy @sowson EFI folder. Is that right?

Yes, just drag and drop into the EFI partition. No installer/ pkg is required. just like Clover (once you have everything setup that is). @czombos has already done 90% of the work in his repo. I started here, but ended up making my own. Ended up quite similar to his EFI plus minus a few things specific to my build.

**Comment by Korvenwin** [comment]
Following your guide, I've booted the system with diferents settings, all of then based on OpenCore.
I've found one PERFECT: Not error in installing, reboots ok, and **NEVER** received the POSTed error. Perhaps you can research this setings.
The build is here: [https://www.tonymacx86.com/threads/the-everything-works-asus-z390-i-gaming-i7-8700k-sapphire-nitro-radeon-rx-vega-64-build.272572/](url)
The settings are at the end of first post: [https://www.tonymacx86.com/attachments/dgpu-oc-efi-zip.463261/](url) (DGPU-OC-EFI)
