### ISSUE TITLE
Cant reach the installer

### ISSUE THREAD

**Issue by MiguelCatalan** [czombos/asus-rog-strix-z390-i-gaming#19]
**(Disclaimer, noobie here) I am a developer so no fear digging into dark places, but this is my first Hackintosh experience.**

## Context
Fails in the boot and cant reach the installer.

I have tried both combinations of bootloader described in the repo and some more:

**Using the EFI for Clover:**
Is stuck ar 
```shell
> iMac-Pro.local com.apple.xpc.launchd[1] (com.apple.bsd.dirhelper.592) <Warning>: Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_ln():com.apple.bsd.dirhelper

> iMac-Pro.local com.apple.xpc.launchd[1] (org.ntp.sntp.205) <Warning>: Service exited with abnormal code: 1
```
**Using the EFI for OpenCore**
Shows the apple logo and when the progress bar reaches 75%, black screen for an hour without any further progress.

**Using the Unibeast from tonymacx86 and a handmade vanilla**
Is stuck at:
```shell
apfs_module_start:1683
```

## My rig:
- Intel i7- 9700K
- Asus rog strix z390-i gaming (duh!)
- Samsung Evo 970 250Gb
- PowerColor AMD RX7500XT
- Kingston HyperX Predator DDR4 2666 PC4-21300 16GB CL13

## Everything up-to-date:
- The BIOS is in v2603 (using the screenshot of this repo)
- The Samsung Evo 970 lastest firmware, and with an NTFS partition (just in case)

What I am doing wrong? Could anyone point me in the right direction?

**Comment by MiguelCatalan** [comment]
I should also add I didn't change the wifi/bt module from the original to the`BCM94360NG M.2 WiFi/ac and BT4LE` yet. (will be in the mail soon).

I think is not related to the error, right?

**Comment by kwuster** [comment]
Correct me if I'm wrong @czombos , but your Clover EFI is deprecated for anything 10.14.3 or higher. @MiguelCatalan , this repo has focused more on OpenCORE now.

This repo also not concerned with Unibeast/ Multibeast from Tonymacx86. While beginner friendly, it's another thing to troubleshoot. AFAIK, Tonymac is still stuck in the stone age with Clover.

Why would you format your SSD in NTFS? I can't think of an FS more anti-macOS than NTFS.... If you need guidance on creating USB installer using OpenCORE, [Dortania](https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/)  has guides for that.

If you have a real Mac... why go thru the pain? Just install onto external USB, boot into it with your real mac first. You must boot into it to complete the installation. Doing this is one less thing to troubleshoot. You need an external SATA or NVMe M-Key enclosure to do this. Once installed, your NVRAM should handle the proper boot flags for mac OS to enter recovery mode/ enter mac os installer to process OS updates like a real mac.

If you are going thru the USB installer, are you following the procedures on Dortania? If not, then this issue is shelved.

**Comment by MiguelCatalan** [comment]
This
> this repo has focused more on OpenCORE now.

and 

> This repo also not concerned with Unibeast/ Multibeast 

I know I know, just showing some context of the tests I did. 

> Why would you format your SSD in NTFS? I can't think of an FS more anti-macOS than NTFS

I could not agree more, but on previous attempts looked I had some issues related to the SSD, so I give it a try from windows (already installed in another SSD in the same machine).

> If you are going thru the USB installer, are you following the procedures on Dortania?

I will give it a try, but... since we have similar hardware, just coping the EFI directory from this repo and pasting it on the EFI partition in the flash drive... should not get "working"?

**Comment by kwuster** [comment]
Your issue is not your 970 Evo. Because I have one on latest FW too. NVMeFix.kext may help quash anything related to SSDs if you are concerned.

I can concur that Unibeast and multibeast comes up with the APFS module failure error for 10.15.4, but this repo is not about that.

Nonetheless , if you are using the usb created from Unibeast and simply replacing the EFI, then this is potentially flawed. Unibeast and clover violates SIP. System Integrity Protection. It has scripts disabling SIP during install. You best create a new vanilla one based on Dortania's guide.

If I have time I'll try to recreate your problem from my end.
