### ISSUE TITLE
Replace module on the motherboard

### ISSUE THREAD

**Issue by feedlike** [czombos/asus-rog-strix-z390-i-gaming#28]
Hello! Tell me if there is somewhere an instruction(tutorial) on how to replace the BCM94360NG M.2 WiFi / ac and BT4LE module on the motherboard. My motherboard asus z390-e Gaming she looks like yours.

**Comment by kwuster** [comment]
There really isn't much to make a tut on. There are a few screws you need to take out in order to take off the heat-spreaders. There are some spring loaded retainers that hold the IO Shield, take photo of how they go in, and then remove them. IO Shield should come off, leaving the WIFI module EMI shield. Unscrew the screws that hold down the EMI shield, and take out the module. The only issue I had was the head sinks were not tall enough to house the BCM9436XX w/ the m.2 adaptor. I had to Dremel/ mill out an opening for my WIFI module to fit.
![IMG_3325](https://user-images.githubusercontent.com/63685362/89402828-c75cd600-d75a-11ea-907a-b83d68e9ec7a.jpg)

**Comment by feedlike** [comment]
Thank you.
